name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      dremio:
        image: dremio/dremio-oss
        ports:
          - 31010:31010
          - 9047:9047
        env:
          DREMIO_JAVA_SERVER_EXTRA_OPTS: -Ddebug.addDefaultUser=true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Dremio environment
        run: |
          echo "DREMIO_SOFTWARE_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DREMIO_SOFTWARE_USERNAME=dremio" >> $GITHUB_ENV
          echo "DREMIO_SOFTWARE_PASSWORD=dremio123" >> $GITHUB_ENV
          echo "DREMIO_DATALAKE=dbt_test_source" >> $GITHUB_ENV
          echo "DREMIO_DATABASE=dbt_test" >> $GITHUB_ENV
          echo "DBT_TEST_USER_1=dbt_test_user_1" >> $GITHUB_ENV
          echo "DBT_TEST_USER_2=dbt_test_user_2" >> $GITHUB_ENV
          echo "DBT_TEST_USER_3=dbt_test_user_3" >> $GITHUB_ENV

      - name: Install AWS CLI
        run: pip install awscli

      - name: Start MinIO Service
        run: |
          docker run -d \
            -p 9000:9000 \
            -p 9001:9001 \
            -e "MINIO_ROOT_USER=admin" \
            -e "MINIO_ROOT_PASSWORD=password" \
            --name minio \
            minio/minio server /data --console-address ":9001"

      - name: Configure AWS credentials for MinIO
        run: |
          echo "AWS_ACCESS_KEY_ID=admin" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=password" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - name: Create MinIO bucket
        run: aws --endpoint-url http://127.0.0.1:9000 s3 mb s3://dbtdremios3

      - name: "Create Dremio S3 Source"
        run: |
          # Install required tools
          sudo apt-get update
          sudo apt-get install -y curl jq

          # Wait for Dremio to be ready
          until curl -s http://127.0.0.1:9047; do
            echo "Waiting for Dremio..."
            sleep 5
          done

          echo "Dremio is up. Proceeding with configuration..."

          # Log in to Dremio to get the auth token
          AUTH_TOKEN=$(curl -s -X POST "http://localhost:9047/apiv2/login" \
            -H "Content-Type: application/json" \
            --data "{\"userName\":\"dremio\", \"password\":\"dremio123\"}" | jq -r .token)

          # Check if AUTH_TOKEN is not empty
          if [ -z "$AUTH_TOKEN" ]; then
            echo "Failed to obtain Dremio auth token"
            exit 1
          fi

          echo "Obtained Dremio auth token"
          echo "$AUTH_TOKEN"

          # Create the S3 source in Dremio
          curl -m 3.0 -s -X PUT "http://localhost:9047/apiv2/source/dbt_test_source" \
            -H "Content-Type: application/json" \
            -H "Authorization: _dremio$AUTH_TOKEN" \
            --data "{\"name\":\"dbt_test_source\",\"config\":{\"credentialType\":\"ACCESS_KEY\",\"accessKey\":\"admin\",\"accessSecret\":\"password\",\"secure\":false,\"externalBucketList\":[],\"enableAsync\":true,\"enableFileStatusCheck\":true,\"rootPath\":\"/\",\"defaultCtasFormat\":\"ICEBERG\",\"propertyList\":[{\"name\":\"fs.s3a.path.style.access\",\"value\":\"true\"},{\"name\":\"fs.s3a.endpoint\",\"value\":\"minio:9000\"},{\"name\":\"dremio.s3.compat\",\"value\":\"true\"}],\"whitelistedBuckets\":[],\"isCachingEnabled\":false,\"maxCacheSpacePct\":100},\"type\":\"S3\",\"metadataPolicy\":{\"deleteUnavailableDatasets\":true,\"autoPromoteDatasets\":false,\"namesRefreshMillis\":3600000,\"datasetDefinitionRefreshAfterMillis\":3600000,\"datasetDefinitionExpireAfterMillis\":10800000,\"authTTLMillis\":86400000,\"updateMode\":\"PREFETCH_QUERIED\"}}"

          echo "S3 Source created in Dremio"

      - name: Install dependencies
        run: |
          pip install -r dev_requirements.txt

      - name: Clean up __pycache__ directories
        run: find . -type d -name "__pycache__" -exec rm -r {} +
      
      - name: Create .env file for tests
        run: |
          mkdir -p tests
          cat <<EOF > tests/.env
          DREMIO_SOFTWARE_HOST=127.0.0.1
          DREMIO_SOFTWARE_USERNAME=dremio
          DREMIO_SOFTWARE_PASSWORD=dremio123
          DREMIO_DATALAKE=dbt_test_source
          DREMIO_DATABASE=dbt_test
          DBT_TEST_USER_1=dbt_test_user_1
          DBT_TEST_USER_2=dbt_test_user_2
          DBT_TEST_USER_3=dbt_test_user_3
          EOF
          pytest tests/caching | tee -a func_test_$(date +%Y_%m_%d).log

      - name: Run Caching tests
        run: |
          pytest tests/caching | tee -a func_test_$(date +%Y_%m_%d).log